### PR TITLE
fixed_several_issues

### LINKED ISSUE #58: Incorrect unit for RAIN_RATE ouput
The output defined as RAIN_RATE in output_var_names has unit of m ( see [https://github.com/NOAA-OWP/cfe/blob/39c18a100dcb5c664900711c8f65f786642f0671/src/bmi_cfe.c#L203]) according to the bmi functions, but the output actually is in mm. 

## Current behavior
Incorrect unit (mm) for RAIN_RATE  output.

## Expected behavior
RAIN_RATE  in m

## Suggested fix:

Since all other variables are in m, we probably want to keep this variable in m, and convert the variable from mm to m within the code.

### LINKED ISSUE #69: "RAIN_RATE" output unit in m, but it is actually mm
This is a small one, but I want to put here so we do not forget. "RAIN_RATE" units based on bmi is meters, but the code output is in mm.

### LINKED ISSUE #124: Should `nash_storage_subsurface` & `nash_storage_surface`  be a 1d arrays of doubles?
In the docs `nash_storage_subsurface` is listed as a double type, but in the parsing code, it looks like this should be a 1d array. @ajkhattak can you clarify this?

https://github.com/NOAA-OWP/cfe/blob/14f334a850981a564ee75b4181c2e9d4a74360b1/src/bmi_cfe.c#L1265

https://github.com/NOAA-OWP/cfe/blob/14f334a850981a564ee75b4181c2e9d4a74360b1/configs/README.md?plain=1#L25

### LINKED ISSUE #125: Add expected unit warning to relevant configuration parameters
Some parameters added around the time of #120 do not warn in units are not included if `CFE_DEBUG` is enabled. Thoughts on adding these warnings?

Im sure i've missed some, but here are the ones that came to mind:

`retention_depth_nash_surface` -> `[m]`
`Kinf_nash_surface` -> `[h^-1]`
`nash_storage_surface` -> `[m]`
`K_nash_surface` -> `[h^-1]`

### PR DESCRIPTION
**Pull request by ajkhattak**
The PR fixed issues created via git issues. These changes don't change the functionality of the model.

1. closed #58  -- fixed RAIN_RATE units
2. closed #69 -- new units are in `m`
3. closed #124 (updated docs)
4. closed #125 (fixed missing units warnings)

## Additions
- None

## Removals
- None

## Changes
- No changes to the functionality

## Testing
1. All existing tests passed

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

File: src/bmi_cfe.c [hunk 1]
```diff
@@ -812,16 +823,31 @@ int read_init_config_cfe(const char* config_file, cfe_state_struct* model)
...
+	  }
 	  continue;
         }
 	if (strcmp(param_key, "retention_depth_nash_surface") == 0) {
 	  model->nash_surface_params.retention_depth = strtod(param_value, NULL);
 	  is_retention_depth_nash_surface_set        = TRUE;
+	  if ((param_units == NULL) || (strlen(param_units) < 1)) {
+#if CFE_DEBUG >= 1
+	    printf ("WARNING: [units] expected for '%s' in config file. [m]\n", param_key);
+#endif
```
Comment (hellkite500) [inline src/bmi_cfe.c:849]: I've looked through the rest of the code and I don't see where the units are actually used for anything, so while printing a warning about missing units is OK, it is somewhat meaningless if the units value is largely ignored and nothing interesting is done with it.

**Review by hellkite500 — APPROVED** [review]
Generally looks good to me, just a small comment on the need for unit parsing and warnings but otherwise, should be mergeable as is...

File: src/bmi_cfe.c (hunk 1 above)
Comment (ajkhattak) [reply src/bmi_cfe.c:849]: that's a valid point, we don't use the units anywhere for anything in the code, the only point I see here is to parse some information to let the user know that units are missing 😊
